### ISSUE TITLE
No update since March 2015

### ISSUE THREAD

**Issue by simon04** [aiomaster/WIWOSM#11]
It seems that there hasn't been an update since March 2015: https://tools.wmflabs.org/wiwosm/wiwosmlog/broken.php shows `created: "Thu, 26 Mar 15 20:27:36 +0000"`

Is the WIWOSM project still maintained?

**Comment by kolossos** [comment]
Daily updates are running now. We are wondering why the broken file is so small. If somebody find missing objects, please post it to us, so that we can check these.
