### ISSUE TITLE
code repo for commons-on-osm.php?

### ISSUE THREAD

**Issue by harry-wood** [aiomaster/WIWOSM#13]
Is this the correct repo to look for `commons-on-osm.php`?

The live deployed version here: https://tools.wmflabs.org/wiwosm/osm-on-ol/commons-on-osm.php  looks like it might be running a different (newer?) version of the code.

I say that because I see for example the [file in this repo refers to an old url](https://github.com/aiomaster/WIWOSM/blob/master/client/commons-on-osm.php#L32) while the live version javascript source can be seen to refer to a working URL for that on wmflabs.org

Where is the source code powering the live site?

**Comment by kolossos** [comment]
I updated the file to live version. 
Have in mind this is only the frontend. 
Backend is not under our direct control:
https://tools.wmflabs.org/geocommons/kml?bbox=14.1534832528,51.574761070859,14.23212991265,51.592331580017

**Comment by harry-wood** [comment]
Cool. Thanks. That answers that question
