### ISSUE TITLE
common-on-osm mouseover popups yellow border styling

### ISSUE THREAD

**Issue by harry-wood** [aiomaster/WIWOSM#18]
On the commons-on-osm when you mouseover a maker to get a popup:

![screen shot 2017-02-09 at 16 55 18](https://cloud.githubusercontent.com/assets/227525/22793740/a2a15704-eee8-11e6-9053-d193bc3063b9.png)

The yellow border styling seems a bit off. Probably would look cleaner without the yellow. Just white. But also there's uneven padding on each side of the image.

**Comment by kolossos** [comment]
Fixed. Thanks for the details.
