### ISSUE TITLE
kolossos's repository and aiomaster's repository (?)

### ISSUE THREAD

**Issue by alexandre-mbm** [aiomaster/WIWOSM#6]
See the issue kolossos/WPONOSM/issues/1 please.
Note that the file's date that is on the Toolserver is 28 Aug 2013.

Which is the license?

**Comment by harry-wood** [comment]
Yes I think there used to be something here https://github.com/kolossos/WPONOSM/issues/1   I remember being confused by this myself.  Guess @kolossos deleted his 'WPONOSM' repo?  So.... confusion resolved, we can close this?

**Comment by kolossos** [comment]
yes we can close it.

**Comment by alexandre-mbm** [comment]
But what is the license for the code in this repository?

**Comment by kolossos** [comment]
We have the license on /client/kml-on-ol.php:

#Contributors: Kolossos, Peter Körner, Alexrk2, Magnus Manske, master 
#Supporters:  river, Raymond, 32X, Markus B., ALE!, Stefan Kühn, dispenser, ...
#License:GPL

For the Server-side stuff User:master can add his prefered license. 
(We should add an license file...)
